# Generated by Django 2.2 on 2020-11-02 10:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес 1')),
                ('address_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовый индекс')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст подвала')),
                ('copyright_text', models.CharField(default='Copyright', max_length=50, verbose_name='Текст копирайта')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип (подвал сайта)')),
            ],
            options={
                'verbose_name': 'Подвал сайта',
                'verbose_name_plural': 'Подвалы сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Favicon (отображается во вкладке сайта)')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('menu_type', models.IntegerField(blank=True, choices=[(0, 'Основное меню'), (1, 'Подвал сайта'), (2, 'Подвал сайта (социальное меню)')], null=True, verbose_name='Тип меню')),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_menus', to='core.FooterSettings', verbose_name='Меню подвала сайта')),
            ],
            options={
                'verbose_name': 'Навигационное меню',
                'verbose_name_plural': 'Навигационные меню',
            },
        ),
        migrations.CreateModel(
            name='NavigationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.IntegerField(choices=[(0, 'Произвольная'), (1, 'По ключу'), (2, 'Телефон'), (3, 'Емейл')], default=1, verbose_name='Тип ссылки')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('publish', models.BooleanField(default=False, verbose_name='Публиковать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Навигационная ссылка',
                'verbose_name_plural': 'Навигационные ссылки',
            },
        ),
    ]
