# Generated by Django 2.2 on 2020-11-03 01:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navigationlinks_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='address_1_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_1_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_2_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_2_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='city_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='city_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_en',
            field=models.CharField(default='Copyright', max_length=50, null=True, verbose_name='Текст копирайта'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_ru',
            field=models.CharField(default='Copyright', max_length=50, null=True, verbose_name='Текст копирайта'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='country_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='country_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='state_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='state_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
