# Generated by Django 2.2 on 2020-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201103_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlinks',
            options={'ordering': ['position'], 'verbose_name': 'Навигационная ссылка', 'verbose_name_plural': 'Навигационные ссылки'},
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
