# Generated by Django 2.2 on 2020-11-13 05:02

import colorfield.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201103_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='first_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Первый цвет фона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='second_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Второй цвет фона'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_path, verbose_name='Логотип (подвал сайта)'),
        ),
        migrations.AlterField(
            model_name='navigationlinks',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_path, verbose_name='Favicon (отображается во вкладке сайта)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(upload_to=core.utils.image_path, verbose_name='Логотип сайта'),
        ),
    ]
