# Generated by Django 2.2 on 2020-11-13 06:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201113_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='background_color',
            field=colorfield.fields.ColorField(default='', max_length=18, verbose_name='Фоновый цвет футера'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='text_color',
            field=colorfield.fields.ColorField(default='', max_length=18, verbose_name='Цвет текста меню'),
        ),
    ]
