# Generated by Django 2.2 on 2020-11-16 13:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201113_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='background_color',
            field=colorfield.fields.ColorField(default='#021d6e', max_length=18, verbose_name='Фоновый цвет футера'),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='text_color',
            field=colorfield.fields.ColorField(default='#090d5e', max_length=18, verbose_name='Цвет текста меню'),
        ),
    ]
