# Generated by Django 2.2 on 2020-11-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201116_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlinks',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page', verbose_name='Страница'),
        ),
    ]
