# Generated by Django 2.2 on 2020-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201117_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='menu_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Основное меню'), (1, 'Подвал сайта'), (2, 'Подвал сайта (социальное меню)'), (3, 'Подвал сайта (номера телефонов/контакты)')], null=True, verbose_name='Тип меню'),
        ),
    ]
