# Generated by Django 2.2 on 2020-11-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201118_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlinks',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
