# Generated by Django 2.2 on 2020-11-02 10:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=350, verbose_name='Заголовок страницы')),
                ('page_keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова страницы')),
                ('page_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание страницы')),
                ('left_side_title', models.CharField(max_length=50, verbose_name='Заголовок страницы (левая сторона)')),
                ('right_side_title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (правая сторона)')),
                ('right_side_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описаниие')),
                ('right_side_background_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фоновое изображение (правая сторона)')),
                ('use_button', models.BooleanField(default=False, verbose_name='Отображать кнопку/ccылку? (правая часть)')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('template', models.IntegerField(blank=True, choices=[(0, 'index.html'), (1, 'about.html'), (2, 'contact.html'), (3, 'news.html'), (4, 'portfolio.html'), (5, 'vacancies.html'), (6, '404.html')], null=True, verbose_name='Шаблон страницы')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ')),
                ('publish', models.BooleanField(default=False, verbose_name='Публиковать')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.IntegerField(blank=True, choices=[(0, 'careers'), (1, 'news'), (2, 'contact'), (3, 'company'), (4, 'second'), (5, 'facts'), (6, 'sector'), (7, 'project'), (8, 'cripto'), (9, 'team'), (10, 'benefit'), (11, 'investor')], null=True, verbose_name='Тип блока')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('background_image', models.ImageField(blank=True, upload_to='', verbose_name='Фоновое изображение')),
                ('use_slider', models.BooleanField(default=False, verbose_name='Использовать слайдер')),
                ('page_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страницы',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('publish', models.BooleanField(default=False, verbose_name='Публиковать')),
            ],
            options={
                'verbose_name': 'Елемент слайдера',
                'verbose_name_plural': 'Елементы слайдера',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_slider', models.IntegerField(blank=True, choices=[(0, 'Обычный'), (1, 'Отзывы')], null=True, verbose_name='Тип слайдера')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('page_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PageBlock')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('show_more_button', models.BooleanField(default=False, verbose_name='Показывать кнопку перехода')),
                ('button_text', models.CharField(blank=True, default='Узнать больше', max_length=50, null=True, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('publish', models.BooleanField(default=False, verbose_name='Публивовать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('page_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PageBlock', verbose_name='Блок страницы')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
