# Generated by Django 2.2 on 2020-11-03 01:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_slideritem_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='button_text_en',
            field=models.CharField(blank=True, default='Узнать больше', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='news',
            name='button_text_ru',
            field=models.CharField(blank=True, default='Узнать больше', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='page',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='page',
            name='left_side_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок страницы (левая сторона)'),
        ),
        migrations.AddField(
            model_name='page',
            name='left_side_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок страницы (левая сторона)'),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='right_side_description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описаниие'),
        ),
        migrations.AddField(
            model_name='page',
            name='right_side_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описаниие'),
        ),
        migrations.AddField(
            model_name='page',
            name='right_side_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок (правая сторона)'),
        ),
        migrations.AddField(
            model_name='page',
            name='right_side_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок (правая сторона)'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='slider',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slider',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
