# Generated by Django 2.2 on 2020-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201103_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['position'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pageblock',
            options={'ordering': ['position'], 'verbose_name': 'Блок страницы', 'verbose_name_plural': 'Блоки страницы'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ['position'], 'verbose_name': 'Елемент слайдера', 'verbose_name_plural': 'Елементы слайдера'},
        ),
        migrations.AddField(
            model_name='news',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
