# Generated by Django 2.2 on 2020-11-04 06:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201103_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='nested_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PageBlock'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(0, 'careers'), (1, 'news'), (2, 'contact'), (3, 'company'), (4, 'second'), (5, 'facts'), (6, 'sector'), (7, 'project'), (8, 'cripto'), (9, 'team'), (10, 'benefit'), (11, 'investor'), (12, 'nested_block')], null=True, verbose_name='Тип блока'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок (название вакансии)')),
                ('title_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок (название вакансии)')),
                ('title_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок (название вакансии)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('publish', models.BooleanField(default=False, verbose_name='Публиковать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageBlock')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('first_name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('first_name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('last_name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Электронный адрес')),
                ('company', models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания, или должность')),
                ('company_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания, или должность')),
                ('company_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания, или должность')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст отзыва')),
                ('text_en', ckeditor.fields.RichTextField(null=True, verbose_name='Текст отзыва')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageBlock')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['position'],
            },
        ),
    ]
