# Generated by Django 2.2 on 2020-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201113_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, max_length=350, verbose_name='Заголовок страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок страницы (SEO/Meta)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок страницы (SEO/Meta)'),
        ),
    ]
