# Generated by Django 2.2 on 2020-11-13 06:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201113_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='left_side_title_color',
            field=colorfield.fields.ColorField(default='', max_length=18, verbose_name='Цвет заголовка страницы (левая сторона)'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='title_color',
            field=colorfield.fields.ColorField(default='', max_length=18, verbose_name='Цвет заголовка'),
        ),
    ]
