# Generated by Django 2.2 on 2020-11-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201113_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='nested_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PageBlock', verbose_name='Вложенный блок'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='page_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page', verbose_name='Для страницы'),
        ),
    ]
