# Generated by Django 2.2 on 2020-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201113_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(0, 'careers'), (1, 'news'), (2, 'contact'), (3, 'company'), (4, 'second'), (5, 'sector'), (6, 'project'), (7, 'cripto'), (8, 'team'), (9, 'benefit'), (10, 'investor'), (11, 'nested_block')], null=True, verbose_name='Тип блока'),
        ),
    ]
