# Generated by Django 2.2 on 2020-11-16 13:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201115_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='left_side_title_color',
            field=colorfield.fields.ColorField(default='#07187b', max_length=18, verbose_name='Цвет заголовка страницы (левая сторона)'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='title_color',
            field=colorfield.fields.ColorField(default='#07187b', max_length=18, verbose_name='Цвет заголовка'),
        ),
    ]
