# Generated by Django 2.2 on 2020-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_review_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
    ]
