# Generated by Django 2.2 on 2020-11-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_pageblock_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='page_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PageBlock'),
        ),
    ]
