# Generated by Django 2.2 on 2020-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20201123_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(0, 'careers_wrapper'), (1, 'careers_item'), (2, 'news_wrapper'), (3, 'contact_wrapper'), (4, 'company_wrapper'), (5, 'second_wrapper'), (6, 'sector_wrapper'), (7, 'project_wrapper'), (8, 'cripto_wrapper'), (9, 'team_wrapper'), (10, 'benefit_wrapper'), (11, 'benefit_item'), (12, 'investor_wrapper'), (13, 'nested_block')], null=True, verbose_name='Тип блока'),
        ),
    ]
