# Generated by Django 2.2 on 2020-11-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20201124_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(0, 'careers_wrapper'), (1, 'news_wrapper'), (2, 'contact_wrapper'), (3, 'company_wrapper'), (4, 'second_wrapper'), (5, 'sector_wrapper'), (6, 'project_wrapper'), (7, 'cripto_wrapper'), (8, 'team_wrapper'), (9, 'benefit_wrapper'), (10, 'investor_wrapper'), (11, 'nested_block')], null=True, verbose_name='Тип блока'),
        ),
    ]
