# Generated by Django 2.2 on 2020-11-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20201124_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='page_block',
        ),
        migrations.AddField(
            model_name='review',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Slider'),
        ),
    ]
